### ISSUE TITLE
Cannot connect to reCaptcha

### ISSUE THREAD

**Issue by privatekenny** [bequadro/instacop#3]
Cannot connect to reCaptcha

**Comment by chrenn** [comment]
Either Google's reCaptcha servers are down or that's an error with your internet connection.

**Comment by kfinest** [comment]
probably my connection then :/

**Comment by privatekenny** [comment]
I just purchased a new modem and router and I'm still getting the error? What could it possibly be?

**Comment by chrenn** [comment]
screenshot?

**Comment by privatekenny** [comment]
https://imgur.com/a/cb0NJ

**Comment by chrenn** [comment]
Come on man, please follow the README.

**Comment by privatekenny** [comment]
I followed it. 
Placed the files in the server root. 
Added 127.0.0.1 w.www.adidas.com to my host file.
